// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTivV1ZUvPl1PEKEK14RkxzDAqWvzdSYQ',
    appId: '1:1023015394794:android:96c200827bde25c5ea2693',
    messagingSenderId: '1023015394794',
    projectId: 'digital-india-11ca4',
    databaseURL: 'https://digital-india-11ca4-default-rtdb.firebaseio.com',
    storageBucket: 'digital-india-11ca4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-R5-zFbmeiUJd4R9nno0-E_-35NHx678',
    appId: '1:1023015394794:ios:747806142d42befbea2693',
    messagingSenderId: '1023015394794',
    projectId: 'digital-india-11ca4',
    databaseURL: 'https://digital-india-11ca4-default-rtdb.firebaseio.com',
    storageBucket: 'digital-india-11ca4.appspot.com',
    androidClientId: '1023015394794-4l0hv5pn315kg0f3iggvbr10mc5sejo9.apps.googleusercontent.com',
    iosBundleId: 'com.example.lemoliteDrawing',
  );
}
